### ISSUE TITLE
TestObjectTestResultWatcher no more supports .getApiKey() or .getDeviceId()

### ISSUE THREAD

**Issue by kevinkirchhof** [testobject/testobject-appium-java-api#16]
Recently I was upgrading testobject's appium java api to version 26. Now I am not able to use TestResultWatchers method to resolve the set Api key in class nor the device ID, which is currently running the tests.

Is this a known issue or is it realted upon my test- / project setup?

I recieve the API via Maven:
```xml
<dependency>
        <groupId>org.testobject</groupId>
        <artifactId>testobject-appium-java-api</artifactId>
        <version>0.0.26</version>
</dependency>
```

My test setup as follows:
```java
import org.junit.Rule;
import org.testobject.appium.junit.TestObjectTestResultWatcher;
...
public TestObjectTestResultWatcher resultWatcher = new TestObjectTestResultWatcher();
...
capabilities.setCapability(TestObjectCapabilities.TESTOBJECT_API_KEY, resultWatcher.getApiKey()); //"Cannot resolve method 'getApiKey()'
```

**Comment by kevinkirchhof** [comment]
Currently the link in readme.md refers to [Suites Setup on TestObject using JUnit](https://help.testobject.com/docs/tools/appium/setups/junit/suites/) where in the missing methods are used.

**Comment by ragog** [comment]
Hi Kevin,

You spotted a stale page in our documentation (which is now being integrated into Sauce Labs' own wiki). I have updated the readme, please refer to https://help.testobject.com/docs/tools/appium/setups/suite-setup/junit/ for the updated docs.

**Comment by kevinkirchhof** [comment]
Hi @ragog,

thanks for this update. But as I figured out youre mentione link: the link targed is the same as the one I've postet in my second comment. Related to this guide it shall be possible to call ResultWatchers selectors e.g. .getApi() as described. But the descibed methods are not available in testobject-appium-java-api version 0.0.26. I was asking, if this might be an issue or just beeing a new feature, which is not yet documented in Sauce Labs' wiki?
@ragog May you could provide further guidance?

Thanks in advance, Kevin

**Comment by ragog** [comment]
Hi @kevinkirchhof,

the key is basically that what used to be the TestObjectTestResultWatcher has now been split into separate classes. You are probably interested in the TestObjectAppiumSuiteWatcher class for your JUnit rule, which contains the methods mentioned.

**Comment by kevinkirchhof** [comment]
Indeed, thank you @ragog.  I was mixing up the old resultWatcher with the new SuiteWatcher one; So it was my mistake. Thanks for your help. :)
